CREATE SEQUENCE user_seq START WITH 1000 INCREMENT BY 1;
CREATE SEQUENCE subscribe_seq START WITH 1000 INCREMENT BY 1;
CREATE SEQUENCE view_seq START WITH 100 INCREMENT BY 1;
CREATE SEQUENCE category_seq START WITH 100 INCREMENT BY 1;
CREATE SEQUENCE profile_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE video_seq START WITH 100000 INCREMENT BY 1;
CREATE SEQUENCE plan_seq START WITH 1 INCREMENT BY 1;
create sequence rating_seq start with 10 increment by 1;


/*
DROP SEQUENCE user_seq;
DROP SEQUENCE subscribe_seq;
DROP SEQUENCE view_seq;
DROP SEQUENCE category_seq;
DROP SEQUENCE profile_seq;
DROP SEQUENCE video_seq;
DROP SEQUENCE plan_seq;
*/