INSERT INTO videos (title, category_id, upload_date) VALUES ('Echoes of Eternity', 106, to_date('05.02.2013','DD.MM.YYYY'));
INSERT INTO videos (title, category_id, upload_date) VALUES ('Journey to Infinity', 107, to_date('08.02.2013','DD.MM.YYYY'));
INSERT INTO videos (title, category_id, upload_date) VALUES ('The Forgotten Kingdom', 108, to_date('12.02.2013','DD.MM.YYYY'));
INSERT INTO videos (title, category_id, upload_date) VALUES ('Shadows of the Past', 109, to_date('15.02.2013','DD.MM.YYYY'));
INSERT INTO videos (title, category_id, upload_date) VALUES ('Kingdom of Dreams', 101, to_date('18.02.2013','DD.MM.YYYY'));
INSERT INTO videos (title, category_id, upload_date) VALUES ('Whispers in the Wind', 102, to_date('22.02.2013','DD.MM.YYYY'));
INSERT INTO videos (title, category_id, upload_date) VALUES ('Echoes of the Soul', 103, to_date('25.02.2013','DD.MM.YYYY'));
INSERT INTO videos (title, category_id, upload_date) VALUES ('Island of Illusions', 104, to_date('28.02.2013','DD.MM.YYYY'));
INSERT INTO videos (title, category_id, upload_date) VALUES ('Starlight Serenade', 105, to_date('04.03.2013','DD.MM.YYYY'));
INSERT INTO videos (title, category_id, upload_date) VALUES ('Realm of Reflections', 106, to_date('08.03.2013','DD.MM.YYYY'));
INSERT INTO videos (title, category_id, upload_date) VALUES ('Twilight Tango', 107, to_date('12.03.2013','DD.MM.YYYY'));
INSERT INTO videos (title, category_id, upload_date) VALUES ('Secrets of the Abyss', 108, to_date('15.03.2013','DD.MM.YYYY'));
INSERT INTO videos (title, category_id, upload_date) VALUES ('Crimson Horizon', 109, to_date('18.03.2013','DD.MM.YYYY'));
INSERT INTO videos (title, category_id, upload_date) VALUES ('Echoes in the Mist', 101, to_date('22.03.2013','DD.MM.YYYY'));
INSERT INTO videos (title, category_id, upload_date) VALUES ('Whispers of the Heart', 102, to_date('25.03.2013','DD.MM.YYYY'));
INSERT INTO videos (title, category_id, upload_date) VALUES ('Sands of Oblivion', 106, to_date('28.11.2012','DD.MM.YYYY'));
INSERT INTO videos (title, category_id, upload_date) VALUES ('Eternal Embrace', 107, to_date('02.12.2012','DD.MM.YYYY'));
INSERT INTO videos (title, category_id, upload_date) VALUES ('Whirlwind Whispers', 108, to_date('05.12.2012','DD.MM.YYYY'));
INSERT INTO videos (title, category_id, upload_date) VALUES ('Dreams of Destiny', 109, to_date('08.12.2012','DD.MM.YYYY'));
INSERT INTO videos (title, category_id, upload_date) VALUES ('Chronicles of Cosmos', 101, to_date('12.12.2012','DD.MM.YYYY'));
INSERT INTO videos (title, category_id, upload_date) VALUES ('Beneath the Surface', 102, to_date('15.12.2012','DD.MM.YYYY'));
INSERT INTO videos (title, category_id, upload_date) VALUES ('Guardians of Gaia', 103, to_date('18.12.2012','DD.MM.YYYY'));
INSERT INTO videos (title, category_id, upload_date) VALUES ('Lost Legends', 104, to_date('22.12.2012','DD.MM.YYYY'));
INSERT INTO videos (title, category_id, upload_date) VALUES ('The Enigma Principle', 105, to_date('25.12.2012','DD.MM.YYYY'));
INSERT INTO videos (title, category_id, upload_date) VALUES ('Dusk Till Dawn', 106, to_date('28.12.2012','DD.MM.YYYY'));
INSERT INTO videos (title, category_id, upload_date) VALUES ('Whispers in the Wind', 107, to_date('02.01.2013','DD.MM.YYYY'));
INSERT INTO videos (title, category_id, upload_date) VALUES ('Echoes of the Soul', 108, to_date('05.01.2013','DD.MM.YYYY'));
INSERT INTO videos (title, category_id, upload_date) VALUES ('Island of Illusions', 109, to_date('08.01.2013','DD.MM.YYYY'));
INSERT INTO videos (title, category_id, upload_date) VALUES ('Starlight Serenade', 101, to_date('12.01.2013','DD.MM.YYYY'));
INSERT INTO videos (title, category_id, upload_date) VALUES ('Realm of Reflections', 102, to_date('15.01.2013','DD.MM.YYYY'));
INSERT INTO videos (title, category_id, upload_date) VALUES ('Twilight Tango', 103, to_date('18.01.2013','DD.MM.YYYY'));
INSERT INTO videos (title, category_id, upload_date) VALUES ('Secrets of the Abyss', 104, to_date('22.01.2013','DD.MM.YYYY'));
INSERT INTO videos (title, category_id, upload_date) VALUES ('Crimson Horizon', 105, to_date('25.01.2013','DD.MM.YYYY'));
INSERT INTO videos (title, category_id, upload_date) VALUES ('Echoes in the Mist', 106, to_date('28.01.2013','DD.MM.YYYY'));
INSERT INTO videos (title, category_id, upload_date) VALUES ('Whispers of the Heart', 107, to_date('01.02.2013','DD.MM.YYYY'));
INSERT INTO videos (title, category_id, upload_date) VALUES ('Echoes of Infinity', 108, to_date('05.02.2015','DD.MM.YYYY'));
INSERT INTO videos (title, category_id, upload_date) VALUES ('Journey to the Future', 109, to_date('08.02.2015','DD.MM.YYYY'));
INSERT INTO videos (title, category_id, upload_date) VALUES ('The Enchanted Forest', 101, to_date('12.02.2015','DD.MM.YYYY'));
INSERT INTO videos (title, category_id, upload_date) VALUES ('Shadows of Tomorrow', 102, to_date('15.02.2015','DD.MM.YYYY'));
INSERT INTO videos (title, category_id, upload_date) VALUES ('Kingdom of Fantasy', 103, to_date('18.02.2015','DD.MM.YYYY'));
INSERT INTO videos (title, category_id, upload_date) VALUES ('Sands of Time', 105, to_date('28.11.2016','DD.MM.YYYY'));
INSERT INTO videos (title, category_id, upload_date) VALUES ('Eternal Journey', 106, to_date('02.12.2016','DD.MM.YYYY'));
INSERT INTO videos (title, category_id, upload_date) VALUES ('Whirlwind of Time', 107, to_date('05.12.2016','DD.MM.YYYY'));
INSERT INTO videos (title, category_id, upload_date) VALUES ('Dreams of Tomorrow', 108, to_date('08.12.2016','DD.MM.YYYY'));
INSERT INTO videos (title, category_id, upload_date) VALUES ('Dusk Till Dusk', 105, to_date('28.12.2016','DD.MM.YYYY'));
INSERT INTO videos (title, category_id, upload_date) VALUES ('Whispers in the Stars', 106, to_date('02.01.2017','DD.MM.YYYY'));
INSERT INTO videos (title, category_id, upload_date) VALUES ('Echoes of the Night', 107, to_date('05.01.2017','DD.MM.YYYY'));
INSERT INTO videos (title, category_id, upload_date) VALUES ('Island of Mystery', 108, to_date('08.01.2017','DD.MM.YYYY'));
INSERT INTO videos (title, category_id, upload_date) VALUES ('The Forgotten Kingdom', 109, to_date('12.02.2017','DD.MM.YYYY'));
INSERT INTO videos (title, category_id, upload_date) VALUES ('Shadows of the Past', 101, to_date('15.02.2017','DD.MM.YYYY'));
INSERT INTO videos (title, category_id, upload_date) VALUES ('Kingdom of Dreams', 102, to_date('18.02.2017','DD.MM.YYYY'));
INSERT INTO videos (title, category_id, upload_date) VALUES ('Echoes of Infinity', 108, to_date('05.02.2020','DD.MM.YYYY'));
INSERT INTO videos (title, category_id, upload_date) VALUES ('Shadows of Tomorrow', 102, to_date('15.02.2020','DD.MM.YYYY'));
INSERT INTO videos (title, category_id, upload_date) VALUES ('Kingdom of Fantasy', 103, to_date('18.02.2020','DD.MM.YYYY'));
INSERT INTO videos (title, category_id, upload_date) VALUES ('Whispers in the Wilderness', 104, to_date('22.02.2020','DD.MM.YYYY'));
INSERT INTO videos (title, category_id, upload_date) VALUES ('Echoes of Reality', 105, to_date('25.02.2020','DD.MM.YYYY'));
INSERT INTO videos (title, category_id, upload_date) VALUES ('Island of Destiny', 106, to_date('28.02.2020','DD.MM.YYYY'));
INSERT INTO videos (title, category_id, upload_date) VALUES ('Sands of Time', 105, to_date('28.11.2021','DD.MM.YYYY'));
INSERT INTO videos (title, category_id, upload_date) VALUES ('Eternal Journey', 106, to_date('02.12.2021','DD.MM.YYYY'));
INSERT INTO videos (title, category_id, upload_date) VALUES ('Whirlwind of Time', 107, to_date('05.12.2021','DD.MM.YYYY'));
INSERT INTO videos (title, category_id, upload_date) VALUES ('Dreams of Tomorrow', 108, to_date('08.12.2021','DD.MM.YYYY'));
INSERT INTO videos (title, category_id, upload_date) VALUES ('Whispers in the Stars', 100, to_date('02.01.2022','DD.MM.YYYY'));
INSERT INTO videos (title, category_id, upload_date) VALUES ('Echoes of the Night', 100, to_date('05.01.2022','DD.MM.YYYY'));
INSERT INTO videos (title, category_id, upload_date) VALUES ('Island of Mystery', 100, to_date('08.01.2022','DD.MM.YYYY'));
INSERT INTO videos (title, category_id, upload_date) VALUES ('Starlight Journey', 100, to_date('12.01.2022','DD.MM.YYYY'));




INSERT INTO videos (title, category_id, upload_date) VALUES ('Inception', 100, to_date('2022-01-01', 'YYYY-MM-DD'));
INSERT INTO videos (title, category_id, upload_date) VALUES ('The Godfather', 100, to_date('2022-01-02', 'YYYY-MM-DD'));
INSERT INTO videos (title, category_id, upload_date) VALUES ('The Shawshank Redemption', 103, to_date('2022-01-03', 'YYYY-MM-DD'));
INSERT INTO videos (title, category_id, upload_date) VALUES ('Schindler''s List', 100, to_date('2022-01-04', 'YYYY-MM-DD'));
INSERT INTO videos (title, category_id, upload_date) VALUES ('The Dark Knight', 105, to_date('2022-01-05', 'YYYY-MM-DD'));
INSERT INTO videos (title, category_id, upload_date) VALUES ('Pulp Fiction', 106, to_date('2022-01-06', 'YYYY-MM-DD'));
INSERT INTO videos (title, category_id, upload_date) VALUES ('The Lord of the Rings: The Return of the King', 107, to_date('2022-01-07', 'YYYY-MM-DD'));
INSERT INTO videos (title, category_id, upload_date) VALUES ('Forrest Gump', 100, to_date('2020-01-08', 'YYYY-MM-DD'));
INSERT INTO videos (title, category_id, upload_date) VALUES ('Star Wars: Episode V - The Empire Strikes Back', 109, to_date('2022-01-09', 'YYYY-MM-DD'));
INSERT INTO videos (title, category_id, upload_date) VALUES ('Inglourious Basterds', 101, to_date('2022-01-10', 'YYYY-MM-DD'));
INSERT INTO videos (title, category_id, upload_date) VALUES ('The Matrix', 102, to_date('2020-01-11', 'YYYY-MM-DD'));
INSERT INTO videos (title, category_id, upload_date) VALUES ('Saving Private Ryan', 103, to_date('2022-01-12', 'YYYY-MM-DD'));
INSERT INTO videos (title, category_id, upload_date) VALUES ('The Green Mile', 104, to_date('2020-01-13', 'YYYY-MM-DD'));
INSERT INTO videos (title, category_id, upload_date) VALUES ('The Pianist', 105, to_date('2022-01-14', 'YYYY-MM-DD'));
INSERT INTO videos (title, category_id, upload_date) VALUES ('The Departed', 106, to_date('2020-01-15', 'YYYY-MM-DD'));
INSERT INTO videos (title, category_id, upload_date) VALUES ('Gladiator', 107, to_date('2022-01-16', 'YYYY-MM-DD'));
INSERT INTO videos (title, category_id, upload_date) VALUES ('The Prestige', 108, to_date('2020-01-17', 'YYYY-MM-DD'));
INSERT INTO videos (title, category_id, upload_date) VALUES ('The Silence of the Lambs', 109, to_date('2022-01-18', 'YYYY-MM-DD'));
INSERT INTO videos (title, category_id, upload_date) VALUES ('The Lion King', 101, to_date('2021-01-19', 'YYYY-MM-DD'));
INSERT INTO videos (title, category_id, upload_date) VALUES ('Back to the Future', 102, to_date('2022-01-20', 'YYYY-MM-DD'));

commit;